defaults: &defaults
  adapter: mysql
  encoding: utf8
  username: root
  password: db4root
  socket: /var/run/mysqld/mysqld.sock

development:
  database: pages_development
  <<: *defaults

test:
  database: pages_test 
  <<: *defaults

production:
  database: pages_production
  <<: *defaults
