defaults: &defaults
  adapter: mysql
  encoding: utf8
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock

development:
  database: pages_development
  <<: *defaults

production:
  database: pages_production
  <<: *defaults


test:
  adapter: sqlite3
  database: db/test.sqlite3
  timeout: 5000

